#!/bin/bash

showTitle () {
    TITLE="DroniX Dev Team's \"cucina\""
    MESSAGE0="What do you wanna do?"

    clear
    echo $TITLE
    echo $MESSAGE0
    echo ""
}

showMenu () {
    
    CHOICE01="Create splash.img"
    CHOICE02="Create logo.rle"

    echo "1) $CHOICE01"
    echo "2) $CHOICE02"
    echo "666) quit"
}

showTitle
showMenu
read CHOICE
case "$CHOICE" in
    "1")
	./scripts/splash01
        ;;
    "2")
	./scripts/logo01
        ;;
    "666")
        exit
        ;;
esac
