#!/bin/bash

showWelcome () {
    TITLE="Welcome to logo.rle creation"
    MESSAGE0="Be sure your logo.png file is in images folder and press OK."

    clear
    echo $TITLE
    echo $MESSAGE0
    echo
}

showSuccess () {
    MESSAGE1="Nice job!"
    MESSAGE2=".rle image has been created. Please be sure your file is named logo.rle nor logo.png.rle"
    MESSAGE3="If you converted more than one image, rename one to logo.rle and add it to your boot.img"

    echo ""
    echo $MESSAGE1
    echo $MESSAGE2
    echo $MESSAGE3
    echo ""
}

showWelcome
if [ -e ./images ]; then
    cd ./images
    # check if ImageMagick is installed and then convert
    if [ -e /usr/bin/convert ]; then
	for i in *.png
	do
	    # I know progress bar is a fake. Don't bother me!
	    echo -n "####"
	    convert -depth 8 $i rgb:$i.raw
	    echo "##########"
	    ../bin/to565 -rle < $i.raw > $i.rle
	    echo "############[100%]"
	done
	for i in *.jpg
	do
	    echo -n "####"
	    convert -depth 8 $i rgb:$i.raw
	    echo "##########"
	    ../bin/to565 -rle < $i.raw > $i.rle
	    echo "############[100%]"
	done 
	
    else
	echo "Please install ImageMagick"
	exit 
    fi

    echo "Created:"
    ls -l *.rle 2> /dev/null
    CHECK=`echo $?`
    if [ CHECK="0" ]; then
	rm *.raw
	showSuccess
    else
	exit 1
    fi
else
    mkdir images
    echo "Please put some image in 'images' folder"
    echo 
fi