#!/bin/bash

DIALOG=${DIALOG=dialog}
TITLE="Welcome to logo.rle creation"
MESSAGE0="Be sure your logo.png file is in images
folder and press OK."

TITLE2="logo.rle successfully created"
MESSAGE2="Nice job!\nNow you can add your new logo.rle to your boot.img"

tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --clear --title "$TITLE" \
--msgbox "$MESSAGE0" 6 50 2> $tempfile

retval=$?

choice=`cat $tempfile`

case $retval in
    0)
	pwd
	if [ -e ./images/logo.png ]; then
	    cd ./images
	    convert -depth 8 logo.png rgb:logo.raw
	    ../bin/to565 -rle < logo.raw > logo.rle
	    if [ -e logo.rle ]; then
		rm logo.raw	       
	    	$DIALOG --clear --title "$TITLE2" \
		    --msgbox "$MESSAGE2" 8 50
	    else
		exit 1
	    fi
	else
	    echo "Cannot find logo.png in images folder"
	    echo 
	fi
	;;
    1)
	echo "Cancel pressed.";;
    255)
	echo "ESC pressed.";;
esac