#!/bin/bash

showWelcome () {
    TITLE="Welcome to splash.img creation"
    MESSAGE0="Be sure your .png or .jpg file is in 'images' folder and press Enter."

    clear
    echo $TITLE
    echo $MESSAGE0
    read
}

showSuccess () {
    MESSAGE1="Nice job!"
    MESSAGE2="Now you can flash your new splash.img to you phone with:"
    MESSAGE3="# fastboot flash splash splash.img"

    echo ""
    echo $MESSAGE1
    echo $MESSAGE2
    echo $MESSAGE3
    echo ""
}

showWelcome
if [ -e ./images ]; then
    cd ./images
    # check if ImageMagick is installed and then convert
    if [ -e /usr/bin/convert ]; then
	for i in *.png
	do
	    # I know progress bar is a fake. Don't bother me!
	    echo -n "####"
	    convert -depth 8 $i rgb:$i.raw
	    echo -n "##########"
	    ../bin/to565 < $i.raw > $i.img
	    echo "##[100%]"
	done
	for i in *.jpg
	do
	    echo -n "####"
	    convert -depth 8 $i rgb:$i.raw
	    echo -n "##########"
	    ../bin/to565 < $i.raw > $i.img
	    echo "##[100%]"
	done 
	
    else
	echo "Please install ImageMagick"
	exit 
    fi

    echo "Created:"
    ls -l *.img 2> /dev/null
    CHECK=`echo $?`
    if [ CHECK="0" ]; then
	rm *.raw
	showSuccess
    else
	exit 1
    fi
else
    mkdir images
    echo "Please put some image in 'images' folder"
    echo 
fi
